name: Setup Common Env
description: Checkout + deps
inputs:
  python-version:
    required: false
    default: '3.11'

runs:
  using: composite
  steps:
    - name: Setup Python (local action)
      uses: ./.github/actions/setup-python
      with:
        python-version: ${{ inputs['python-version'] }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        pip install -r requirements.txt
