name: PR Work flow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  pr-files:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{steps.step-files.outputs.files}}
        
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch main branch
        run: git fetch origin main
      - name: Getting files changed vs main
        id: step-files
        run: |
          files=$(git diff --name-only origin/main...HEAD | paste -sd ',' -)
          echo "Files change: $files"
          echo "files=$files" >> $GITHUB_OUTPUT

  lint:
    needs: pr-files
    uses: ./.github/workflows/run-flake8.yml
    with:
      file_under_test: ${{needs.pr-files.outputs.changed-files}}
      python-version: '3.11'
