name: PR Work flow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  pr-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unshallow repository
        run: git fetch --unshallow
      - name: Obtener base y head
        run: |
          echo "base=${{ github.event.pull_request.base.sha }}"
          echo "head=${{ github.event.pull_request.head.sha }}"
      - name: Listar archivos cambiados en el PR
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}

  lint:
    uses: ./.github/workflows/run-flake8.yml
    with:
      file_under_test: 'test'
      python-version: '3.11'
