name: Run Flake8

on:
  workflow_call:
    inputs:
      file_under_test:
        type: string
        default: '.'
      python-version:
        type: string
        default: '3.11'

jobs:
  preparer-matrix:
    runs-on: ubuntu-latest
    outputs:
      file: ${{steps.matrix-arrays.outputs.result || inputs.file_under_test}} 
    steps:
      - name: Take files from pull request
        if: ${{ github.event_name }} == 'pull_request'
        uses: actions/github-script@v6
        id: matrix-arrays
        with:
          script: "return inputs.file_under_test.split(',')"
          result-encoding: json
      - name: Take files from other events
        if: ${{ github.event_name }} != 'pull_request'
        run: echo "Let default value"

  lint:
    needs: preparer-matrix
    
    strategy:
      matrix:
        file: ${{ fromJSON(needs.preparer-matrix.outputs.file)}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python (local action)
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ inputs['python-version'] }}

      - name: Install flake8
        run: pip install flake8

      - name: Execute Flake8
        run: |
          echo "Executing flake8 on ${{ matrix.file }}"
          flake8 ${{ matrix.file }}
