name: Run Flake8

on:
  workflow_call:
    inputs:
      file_under_test:
        required: false
        type: string
        default: '.'
      python-version:
        description: Python version
        required: false
        type: string
        default: '3.11'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install flake8
        run: pip install flake8
      - name: Execute Flake8 on
        run: |
          echo "Executing flake 8 on file ${{ inputs.file_under_test }}"
          flake8 inputs.file_under_test
