name: Run Flake8

on:
  workflow_call:
    inputs:
      file_under_test:
        type: string
        default: '.'
      python-version:
        type: string
        default: '3.11'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python (local action)
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ inputs['python-version'] }}

      - name: Install flake8
        run: pip install flake8

      - name: Execute Flake8
        run: |
          echo "Executing flake8 on ${{ inputs.file_under_test }}"
          flake8 ${{ inputs.file_under_test }}
